# Generated by Django 2.2.28 on 2023-01-21 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from home.models import DEFAULT_PLANS


def forwards_func(apps, schema_editor):
    plan_model = apps.get_model("home", "plan")
    for plan in DEFAULT_PLANS:
        plan_model.objects.create(**plan)


def reverse_func(apps, schema_editor):
    pass # if not declared, it does not allow reversing migration


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0001_load_initial_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Created At"),
                ),
                ("name", models.CharField(help_text="Name", max_length=50)),
                ("description", models.TextField(help_text="Description")),
                (
                    "type",
                    models.CharField(
                        choices=[("Web", "Web"), ("Mobile", "Mobile")],
                        help_text="Type",
                        max_length=50,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("Django", "Django"),
                            ("React Native", "React Native"),
                        ],
                        help_text="Framework",
                        max_length=50,
                    ),
                ),
                (
                    "domain_name",
                    models.CharField(help_text="Domain name", max_length=50),
                ),
                (
                    "screenshot",
                    models.URLField(blank=True, help_text="Screenshot", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Created At"),
                ),
                ("name", models.CharField(help_text="Name", max_length=50)),
                ("description", models.TextField(help_text="Description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price", max_digits=13
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Created At"),
                ),
                ("active", models.BooleanField(help_text="Active")),
                (
                    "app",
                    models.ForeignKey(
                        help_text="App",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.App",
                    ),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        help_text="Plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_plan",
                        to="home.Plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(code=forwards_func, reverse_code=reverse_func),
    ]
